tools:
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: get_user_details
      description: Get the details of a user, including their reservations.
      parameters:
        type: object
        properties:
          user_id:
            type: string
            description: The user ID, such as 'sara_doe_496'.
        required:
        - user_id
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: get_reservation_details
      description: Get the details of a reservation.
      parameters:
        type: object
        properties:
          reservation_id:
            type: string
            description: The reservation ID, such as '8JX2WO'.
        required:
        - reservation_id
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: get_flight_status
      description: Get the status of a flight.
      parameters:
        type: object
        properties:
          flight_number:
            type: string
            description: The flight number.
          date:
            type: string
            description: The date of the flight.
        required:
        - flight_number
        - date
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: list_all_airports
      description: Returns a list of all available airports.
      parameters:
        type: object
        properties: {}
        required: []
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: search_direct_flight
      description: Search for direct flights between two cities on a specific date.
      parameters:
        type: object
        properties:
          origin:
            type: string
            description: The origin city airport in three letters, such as 'JFK'.
          destination:
            type: string
            description: The destination city airport in three letters, such as 'LAX'.
          date:
            type: string
            description: The date of the flight in the format 'YYYY-MM-DD', such as '2024-01-01'.
        required:
        - origin
        - destination
        - date
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: search_onestop_flight
      description: Search for one-stop flights between two cities on a specific date.
      parameters:
        type: object
        properties:
          origin:
            type: string
            description: The origin city airport in three letters, such as 'JFK'.
          destination:
            type: string
            description: The destination city airport in three letters, such as 'LAX'.
          date:
            type: string
            description: The date of the flight in the format 'YYYY-MM-DD', such as '2024-05-01'.
        required:
        - origin
        - destination
        - date
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: cancel_reservation
      description: Cancel the whole reservation.
      parameters:
        type: object
        properties:
          reservation_id:
            type: string
            description: The reservation ID, such as 'ZFA04Y'.
        required:
        - reservation_id
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: update_reservation_flights
      description: Update the flight information of a reservation.
      parameters:
        type: object
        properties:
          reservation_id:
            type: string
            description: The reservation ID, such as 'ZFA04Y'.
          cabin:
            type: string
            description: The cabin class of the reservation
            enum:
            - business
            - economy
            - basic_economy
          flights:
            type: string
            description: 'An array of objects containing details about each piece of flight in the ENTIRE new reservation. Even if the a flight segment is not changed, it should still be included in the
              array. Provide as JSON-serialized array of {flight_number (string): Flight number, such as ''HAT001''.; date (string): The date for the flight in the format ''YYYY-MM-DD'', such as ''2024-05-01''.}'
          payment_id:
            type: string
            description: The payment id stored in user profile, such as 'credit_card_7815826', 'gift_card_7815826', 'certificate_7815826'.
        required:
        - reservation_id
        - cabin
        - flights
        - payment_id
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: update_reservation_baggages
      description: Update the baggage information of a reservation.
      parameters:
        type: object
        properties:
          reservation_id:
            type: string
            description: The reservation ID, such as 'ZFA04Y'
          total_baggages:
            type: integer
            description: The updated total number of baggage items included in the reservation.
          nonfree_baggages:
            type: integer
            description: The updated number of non-free baggage items included in the reservation.
          payment_id:
            type: string
            description: The payment id stored in user profile, such as 'credit_card_7815826', 'gift_card_7815826', 'certificate_7815826'.
        required:
        - reservation_id
        - total_baggages
        - nonfree_baggages
        - payment_id
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: update_reservation_passengers
      description: Update the passenger information of a reservation.
      parameters:
        type: object
        properties:
          reservation_id:
            type: string
            description: The reservation ID, such as 'ZFA04Y'.
          passengers:
            type: string
            description: 'An array of objects containing details about each passenger. Provide as JSON-serialized array of {first_name (string): Passenger''s first name; last_name (string): Passenger''s
              last name; dob (string): Date of birth in YYYY-MM-DD format}'
        required:
        - reservation_id
        - passengers
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: send_certificate
      description: Send a certificate to a user. Be careful!
      parameters:
        type: object
        properties:
          user_id:
            type: string
            description: The ID of the user to book the reservation, such as 'sara_doe_496'.
          amount:
            type: integer
            description: The amount of the certificate to send.
        required:
        - user_id
        - amount
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: book_reservation
      description: Book a reservation.
      parameters:
        type: object
        properties:
          user_id:
            type: string
            description: The ID of the user to book the reservation such as 'sara_doe_496'`.
          origin:
            type: string
            description: The IATA code for the origin city such as 'SFO'.
          destination:
            type: string
            description: The IATA code for the destination city such as 'JFK'.
          flight_type:
            type: string
            description: The type of flight such as 'one_way' or 'round_trip'.
            enum:
            - round_trip
            - one_way
          cabin:
            type: string
            description: The cabin class such as 'basic_economy', 'economy', or 'business'.
            enum:
            - business
            - economy
            - basic_economy
          flights:
            type: string
            description: 'An array of objects containing details about each piece of flight. Provide as JSON-serialized array of {flight_number (string): Flight number, such as ''HAT001''.; date (string):
              The date for the flight in the format ''YYYY-MM-DD'', such as ''2024-05-01''.}'
          passengers:
            type: string
            description: 'An array of objects containing details about each passenger. Provide as JSON-serialized array of {first_name (string): Passenger''s first name; last_name (string): Passenger''s
              last name; dob (string): Date of birth in YYYY-MM-DD format}'
          payment_methods:
            type: string
            description: 'An array of objects containing details about each payment method. Provide as JSON-serialized array of {payment_id (string): Unique identifier for the payment; amount (integer):
              Payment amount in dollars}'
          total_baggages:
            type: integer
            description: The total number of baggage items to book the reservation.
          nonfree_baggages:
            type: integer
            description: The number of non-free baggage items to book the reservation.
          insurance:
            type: string
            description: Whether the reservation has insurance.
            enum:
            - 'yes'
            - 'no'
        required:
        - user_id
        - origin
        - destination
        - flight_type
        - cabin
        - flights
        - passengers
        - payment_methods
        - total_baggages
        - nonfree_baggages
        - insurance
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: calculate
      description: Calculate the result of a mathematical expression.
      parameters:
        type: object
        properties:
          expression:
            type: string
            description: The mathematical expression to calculate, such as '2 + 2'. The expression can contain numbers, operators (+, -, *, /), parentheses, and spaces.
        required:
        - expression
- class_name: verl.tools.tau3_live_tool.Tau3LiveTool
  config:
    type: native
  tool_schema:
    type: function
    function:
      name: transfer_to_human_agents
      description: "Transfer the user to a human agent, with a summary of the user's issue.\n\nOnly transfer if\n -  the user explicitly asks for a human agent\n -  given the policy and the available tools,\
        \ you cannot solve the user's issue."
      parameters:
        type: object
        properties:
          summary:
            type: string
            description: A summary of the user's issue.
        required:
        - summary
